[package]
name = "de_res"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "res_de"
path = "src/lib.rs"

[dependencies]
hypermelon = "0.5.5"
poloto = "18.0.6"
rayon = "1.7.0"
savefile = "0.12.0"
